seed: 1029
device: cuda
model: saint

valid_size: 2500000
epoch_valid_size: 1000000

window_size: 100
stride_size: 100

n_epochs: 10
warmup_steps: 4000
accumulation_steps: 1

train_loader_params:
  batch_size: 128
  shuffle: true
  num_workers: 0
  pin_memory: true

valid_loader_params:
  batch_size: 128
  shuffle: false
  num_workers: 2
  pin_memory: true

encoder_config:
  vocab_size: 13525  # number of unique questions + padding id + start id
  category_size: 9  # number of unique question part + padding id + start id
  content_embedding_size: 256
  embedding_size: 64
  hidden_size: 256
  num_hidden_layers: 12
  num_attention_heads: 8
  relative_attention_num_buckets: 32
  lag_time_scale_alpha: 2.5
  intermediate_size: 1024
  hidden_act: gelu
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  initializer_range: 0.02
  layer_norm_eps: 1.0e-12
  pad_token_id: 0
  gradient_checkpointing: false
  is_decoder: false
  add_cross_attention: false

decoder_config:
  response_embedding_size: 128
  embedding_size: 128
  hidden_size: 256
  num_hidden_layers: 12
  num_attention_heads: 8
  relative_attention_num_buckets: 32
  lag_time_scale_alpha: 2.5
  intermediate_size: 1024
  hidden_act: gelu
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  initializer_range: 0.02
  layer_norm_eps: 1.0e-12
  pad_token_id: 0
  gradient_checkpointing: false
  is_decoder: true
  add_cross_attention: true
  max_lag_minutes: 1440
  max_elapsed_seconds: 300

optimizer_params:
  lr: 3.0e-4
  betas:
    - 0.9
    - 0.99
  eps: 1.0e-8
